# Generated by Django 3.2.9 on 2022-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulistings',
            name='nuotrauka',
            field=models.ImageField(upload_to='images'),
        ),
    ]
